runtime: python39
entrypoint: serve
service: maquicontrol-frontend-new-version

handlers:
  - url: /(.+\..+)$
    static_files: \1
    upload: .+\..+
  - url: /.*
    static_files: index.html
    upload: index.html
